version: '3.8'
services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: rotten_papers
    volumes:
      - ./database:/docker-entrypoint-initdb.d  
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306" 
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/RP:/app
       - node_modules:/frontend/RP/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/rotten_papers:/app/rotten_papers
    environment:
      - DATABASE_URL=mysql://root:password@mysql_db:3306/rotten_papers
      - DEBUG=1
    depends_on:
      - db  # Ahora el backend depende de la base de datos
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  node_modules:
