version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/RP:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/rotten_papers:/app/rotten_papers
    environment:
      - DEBUG=1
    depends_on:
      - db  # Ahora el backend depende de la base de datos
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rotten_papers
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # Volumen para inicializar la BD con el seed SQL
      - db_data:/var/lib/mysql  # Volumen para persistir los datos
    ports:
      - "3306:3306"  # Puerto MySQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
