# Generated by Django 5.1.1 on 2024-09-10 20:53

import django.core.validators
import django.db.models.deletion
import rp_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('lastname1', models.CharField(max_length=250)),
                ('lastname2', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[rp_app.models.validate_no_numbers])),
                ('lastname1', models.CharField(max_length=50, validators=[rp_app.models.validate_no_numbers])),
                ('lastname2', models.CharField(blank=True, max_length=50, null=True, validators=[rp_app.models.validate_no_numbers])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('synopsis', models.TextField()),
                ('cover', models.URLField(blank=True, max_length=250, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.autores')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.genero')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Librogenero',
            fields=[
                ('genreB_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.genero')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.libros')),
            ],
            options={
                'db_table': 'Libro_Genero',
            },
        ),
    ]
