# Generated by Django 5.1.1 on 2024-09-24 21:14

import django.core.validators
import django.db.models.deletion
import rp_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('lastname1', models.CharField(blank=True, max_length=250, null=True)),
                ('lastname2', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[rp_app.models.validate_no_numbers])),
                ('lastname1', models.CharField(max_length=50, validators=[rp_app.models.validate_no_numbers])),
                ('lastname2', models.CharField(blank=True, max_length=50, null=True, validators=[rp_app.models.validate_no_numbers])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('synopsis', models.TextField()),
                ('cover', models.URLField(blank=True, max_length=250, null=True)),
                ('rating', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.authors')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.genres')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Book_Genre',
            fields=[
                ('genreB_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.books')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.genres')),
            ],
            options={
                'db_table': 'book_genre',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.users')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.genres')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.users')),
            ],
            options={
                'db_table': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp_app.users')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
    ]
